name: diabetes_management
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  app_links: ^6.4.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.2.0
  intl: ^0.19.0
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.2
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  logger: ^2.0.2+1
  flutter_secure_storage: ^9.2.2
  provider: ^6.1.4
  flutter_typeahead: ^5.2.0
  translator: ^1.0.3+1
  image_picker: ^1.1.2 # لاختيار الصور من المعرض
  permission_handler: ^11.3.1 # لإدارة الأذونات
  cached_network_image: ^3.3.1
  
dependency_overrides:
  flutter_keyboard_visibility: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
