# Generated by Django 5.1.6 on 2025-04-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_remove_dailyreminder_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreminder',
            name='medication_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
