# Generated by Django 5.1.5 on 2025-04-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_doctorprofile_name_remove_patientprofile_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='age',
        ),
    ]
