# Generated by Django 5.1.5 on 2025-04-14 02:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_doctorpatientrelation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='doctorpatientrelation',
            constraint=models.CheckConstraint(condition=models.Q(('doctor', models.F('patient')), _negated=True), name='doctor_patient_different'),
        ),
    ]
