# Generated by Django 5.1.5 on 2025-04-14 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_doctorpatientrelation_doctor_patient_different'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorpatientrelation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='doctorpatientrelation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
