# Generated by Django 5.1.5 on 2025-04-14 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0006_alter_doctorpatientrelation_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlucoseTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose_type', models.CharField(choices=[('FBS', 'Fasting Blood Sugar'), ('PPBS', 'Postprandial Blood Sugar'), ('RBS', 'Random Blood Sugar')], max_length=4)),
                ('glucose_value', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glucose_readings', to='profiles.patientprofile')),
            ],
        ),
    ]
