# Generated by Django 5.1.5 on 2025-04-29 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetescare', '0001_initial'),
        ('profiles', '0006_alter_doctorpatientrelation_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='analysis_images/')),
                ('description', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_images', to='profiles.patientprofile')),
            ],
        ),
    ]
