# Generated by Django 5.1.5 on 2025-04-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetescare', '0002_analysisimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisimage',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
